# Generated by Django 5.2.2 on 2025-06-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Font Awesome class', max_length=50)),
            ],
            options={
                'verbose_name': 'Kategori Layanan',
                'verbose_name_plural': 'Kategori Layanan',
            },
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('persyaratan', models.TextField()),
                ('prosedur', models.TextField()),
                ('waktu_penyelesaian', models.CharField(max_length=100)),
                ('biaya', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.kategorilayanan')),
            ],
            options={
                'verbose_name': 'Layanan',
                'verbose_name_plural': 'Layanan',
            },
        ),
    ]
