# Generated by Django 5.2.2 on 2025-06-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategori Berita',
                'verbose_name_plural': 'Kategori Berita',
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('konten', models.TextField()),
                ('ringkasan', models.TextField(max_length=300)),
                ('gambar', models.ImageField(upload_to='berita/')),
                ('penulis', models.CharField(max_length=100)),
                ('tanggal_publish', models.DateTimeField()),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.kategoriberita')),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
                'ordering': ['-tanggal_publish'],
            },
        ),
    ]
