# Generated by Django 5.2.2 on 2025-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SejarahDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('tahun', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sejarah Desa',
                'verbose_name_plural': 'Sejarah Desa',
                'ordering': ['tahun'],
            },
        ),
        migrations.CreateModel(
            name='StrukturOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='struktur/')),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Struktur Organisasi',
                'verbose_name_plural': 'Struktur Organisasi',
                'ordering': ['urutan'],
            },
        ),
    ]
