# Generated by Django 5.2.2 on 2025-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('prioritas', models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi'), ('urgent', 'Urgent')], default='sedang', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_berakhir', models.DateTimeField()),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diupdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='ProfilDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_desa', models.CharField(max_length=100)),
                ('kepala_desa', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('deskripsi_singkat', models.TextField()),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='profil/')),
                ('foto_kantor', models.ImageField(blank=True, upload_to='profil/')),
            ],
            options={
                'verbose_name': 'Profil Desa',
                'verbose_name_plural': 'Profil Desa',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='slider/')),
                ('link', models.URLField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.IntegerField(default=0)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='StatistikDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_penduduk', models.IntegerField()),
                ('jumlah_kk', models.IntegerField()),
                ('luas_wilayah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah_rt', models.IntegerField()),
                ('jumlah_rw', models.IntegerField()),
                ('tahun_data', models.IntegerField()),
                ('diupdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistik Desa',
                'verbose_name_plural': 'Statistik Desa',
            },
        ),
    ]
