# Generated by Django 5.2.2 on 2025-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('tipe', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], max_length=10)),
                ('file', models.ImageField(blank=True, upload_to='galeri/')),
                ('video_url', models.URLField(blank=True)),
                ('tanggal', models.DateField()),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'Galeri',
                'ordering': ['-tanggal'],
            },
        ),
    ]
